export interface ActifIncorporel {
    id?: number; // Optional as it will be generated by the backend
    nature_ActifIncorporel: string;
    identifiantEntreprise: string;
    onereuxGratuit: string;
    raisonSociale: string;
    qualiteEntreprise: string;
    natureRelationEntreprise: string;  
  }
  