export interface ActifCorporel {
    id?: number; // Optional as it will be generated by the backend
    nature_ActifCorporel: string;
    identifiantEntreprise: string;
    raisonSociale: string;
    qualiteEntreprise: string;
    natureRelationEntreprise: string;  
  }