import { Entreprise } from "./entreprise";

export interface Declaration {
    id?: number; // Optional since it will be generated by the backend
    exercice: string;
    typedeclaration: string;
    dateDebut: string;
    dateFin: string;
    naturedateFin: string;
    entreprise?: any; // Assuming Entreprise is also defined in TypeScript
  }
  