export interface DescriptionTransactionsRegimeFiscalPrivilegie {
    id?: number; // Optional as it will be generated by the backend
    descriptionTransactionsRegimeFiscalPrivilegie : string; // Assuming this will be handled separately
    declaration?: any;
  }
  