export interface DescriptionTransactionsRegimeFiscalPrivilegie {
    id?: number; // Optional as it will be generated by the backend
    description : string; // Assuming this will be handled separately
    declaration?: any;
  }
  