export interface InfoED {
    id?: number; // Optional as it will be generated by the backend
    qualiteEntreprise: string;
    descriptionActivitePrincipale: string;
    changementsActivite: string;
    description2: string;
    declaration?: any; // Assuming this will be handled separately
  }
  